id: P003007
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:58.501174
source_metadata:
  id: bdr:W3CN7892
  title: ཚད་མ་ཀུན་བཏུས་དང་རྣམ་འགྲེལ་གྱི་རྩ་འགྲེལ་གཅེས་བཏུས།
  author: ''
  volumes:
    76991d3aceb84e0290627a3e85bd7f8a:
      image_group_id: I3CN7894
      title: ''
      volume_number: 1
      total_pages: 644
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
